require("trimonovds.plugin-config.lsp")
require("trimonovds.plugin-config.treesitter")
require("trimonovds.plugin-config.lualine")
require("trimonovds.plugin-config.nvim-tree")
require("trimonovds.plugin-config.telescope")
require("trimonovds.plugin-config.comment")
require("trimonovds.plugin-config.gitsigns")
require("trimonovds.plugin-config.toggleterm")
require("trimonovds.plugin-config.colorscheme")
require("trimonovds.plugin-config.cmp")
require("trimonovds.plugin-config.comment")

